### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by denisdemaisbr** [moteus/lua-vararg#2]
Hi, this library is compatible and testes with what version of lua ?

Thanks!

**Comment by moteus** [comment]
It compatiable with Lua >= 5.1. And with LuaJIT.
Does not test on other Versions/Implementations.
But I think Lua version use quite basic functions so should be quite portable.

PS. This is list of tested versions https://github.com/moteus/lua-vararg/blob/master/.travis.yml#L7-L14

**Comment by denisdemaisbr** [comment]
thanks for reply!
this library is very usefully!
